### ISSUE TITLE
Need help to set the SCBK

### ISSUE THREAD

**Issue by DeepaGRao** [bytedreamer/OSDP.Net#73]
We are using below code snippet to connect to the PD.

1. Default Key is used initially to establish connection
byte[] bytes = new byte[] { 0x30, 0x31, 0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39,0x3A,0x3B,0x3C,0x3D,0x3E,0x3F };
panel.AddDevice(_connectionId, deviceAddress, true, true,bytes);

2. Next we are trying to set the new SCBK using the below EncryptionKeySet method.
byte[] bytes1 = new byte[]
{
0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07
};
bool successfulSet = await panel.EncryptionKeySet(_connectionId, deviceAddress, new EncryptionKeyConfiguration(KeyType.SecureChannelBaseKey, bytes1));

But after sometime we get an exception as "The operation has timed out". Below is the detailed stack trace. Can you please guide us on why this error can happen?

   at OSDP.Net.ControlPanel.<SendCommand>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OSDP.Net.ControlPanel.<EncryptionKeySet>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSDPSample.Program.<Main>d__2.MoveNext()

**Comment by bytedreamer** [comment]
Recently added security check to ensure that clear text messages aren't process while in Secure Channel Mode didn't account for the KeySet command. The PD will return an ACK in clear text after the key has been changed.

This issue has been fixed in Release 2.1.3
